package com.hcicloud.sap.service.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SpeechToTextDelegate", targetNamespace = "http://webservice.sap.hcicloud.com/")
public interface SpeechToTextDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns com.hcicloud.sap.webservice.SaResult
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getStatus", targetNamespace = "http://webservice.sap.hcicloud.com/", className = "com.hcicloud.sap.webservice.GetStatus")
	@ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://webservice.sap.hcicloud.com/", className = "com.hcicloud.sap.webservice.GetStatusResponse")
	public SaResult getStatus(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "transFinished", targetNamespace = "http://webservice.sap.hcicloud.com/", className = "com.hcicloud.sap.webservice.TransFinished")
	@ResponseWrapper(localName = "transFinishedResponse", targetNamespace = "http://webservice.sap.hcicloud.com/", className = "com.hcicloud.sap.webservice.TransFinishedResponse")
	public void transFinished(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg3
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "speechAnalysis", targetNamespace = "http://webservice.sap.hcicloud.com/", className = "com.hcicloud.sap.webservice.SpeechAnalysis")
	@ResponseWrapper(localName = "speechAnalysisResponse", targetNamespace = "http://webservice.sap.hcicloud.com/", className = "com.hcicloud.sap.webservice.SpeechAnalysisResponse")
	public String speechAnalysis(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") SaParams arg2,
			@WebParam(name = "arg3", targetNamespace = "") List<SpeechFile> arg3);

}
