--------------------------------------------------------
--  �ļ��Ѵ��� - ������-ʮ����-21-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table QUALITY_ARTIFICAL_ITEM
--------------------------------------------------------

  CREATE TABLE "QUALITY_ARTIFICAL_ITEM" 
   (	"UUID" VARCHAR2(32 BYTE), 
	"NAME" VARCHAR2(64 BYTE), 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"SCORE" VARCHAR2(32 BYTE), 
	"TYPE" VARCHAR2(32 BYTE), 
	"CREATE_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_ARTIFICAL_ITEM"."UUID" IS '����';
 
   COMMENT ON COLUMN "QUALITY_ARTIFICAL_ITEM"."NAME" IS '�淶���';
 
   COMMENT ON COLUMN "QUALITY_ARTIFICAL_ITEM"."CONTENT" IS '�淶����';
 
   COMMENT ON COLUMN "QUALITY_ARTIFICAL_ITEM"."SCORE" IS '��ֵ';
 
   COMMENT ON COLUMN "QUALITY_ARTIFICAL_ITEM"."TYPE" IS '�ȼ�';
 
   COMMENT ON COLUMN "QUALITY_ARTIFICAL_ITEM"."CREATE_TIME" IS '����ʱ��';
--------------------------------------------------------
--  DDL for Table QUALITY_AUTOLEXICON
--------------------------------------------------------

  CREATE TABLE "QUALITY_AUTOLEXICON" 
   (	"UUID" VARCHAR2(32 BYTE), 
	"NAME" VARCHAR2(64 BYTE), 
	"CONTENT" VARCHAR2(2408 BYTE), 
	"AUTORULE_ID" VARCHAR2(32 BYTE), 
	"UPDATE_USER_ID" VARCHAR2(50 BYTE), 
	"UPDATE_TIME" DATE, 
	"STATE" NUMBER, 
	"FLAG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_AUTOLEXICON"."UUID" IS '����ID';
 
   COMMENT ON COLUMN "QUALITY_AUTOLEXICON"."NAME" IS '�������';
 
   COMMENT ON COLUMN "QUALITY_AUTOLEXICON"."CONTENT" IS '��������';
 
   COMMENT ON COLUMN "QUALITY_AUTOLEXICON"."AUTORULE_ID" IS '�����ʼ����ID';
 
   COMMENT ON COLUMN "QUALITY_AUTOLEXICON"."UPDATE_USER_ID" IS '�޸���';
 
   COMMENT ON COLUMN "QUALITY_AUTOLEXICON"."UPDATE_TIME" IS '�޸�ʱ��';
 
   COMMENT ON COLUMN "QUALITY_AUTOLEXICON"."STATE" IS '״̬��1 ��ʾ����0��ʾ����';
 
   COMMENT ON COLUMN "QUALITY_AUTOLEXICON"."FLAG" IS '�Ƿ���ͨ�ôʣ�1��ʾ�ǣ�0��ʾ����';
--------------------------------------------------------
--  DDL for Table QUALITY_AUTOLOGIC
--------------------------------------------------------

  CREATE TABLE "QUALITY_AUTOLOGIC" 
   (	"UUID" VARCHAR2(32 BYTE), 
	"CONTENT" VARCHAR2(256 BYTE), 
	"AUTORULE_ID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_AUTOLOGIC"."UUID" IS '����ID';
 
   COMMENT ON COLUMN "QUALITY_AUTOLOGIC"."CONTENT" IS '�����߼�����';
 
   COMMENT ON COLUMN "QUALITY_AUTOLOGIC"."AUTORULE_ID" IS '�����ʼ����ID';
--------------------------------------------------------
--  DDL for Table QUALITY_AUTOPHRASE
--------------------------------------------------------

  CREATE TABLE "QUALITY_AUTOPHRASE" 
   (	"UUID" VARCHAR2(32 BYTE), 
	"NAME" VARCHAR2(64 BYTE), 
	"CONTENT" VARCHAR2(256 BYTE), 
	"AUTORULE_ID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_AUTOPHRASE"."UUID" IS '����ID';
 
   COMMENT ON COLUMN "QUALITY_AUTOPHRASE"."NAME" IS '�������';
 
   COMMENT ON COLUMN "QUALITY_AUTOPHRASE"."CONTENT" IS '��������';
 
   COMMENT ON COLUMN "QUALITY_AUTOPHRASE"."AUTORULE_ID" IS '�����Զ�����ID';
--------------------------------------------------------
--  DDL for Table QUALITY_AUTORULE
--------------------------------------------------------

  CREATE TABLE "QUALITY_AUTORULE" 
   (	"UUID" VARCHAR2(32 BYTE), 
	"NAME" VARCHAR2(64 BYTE), 
	"CONTENT" LONG, 
	"UPDATE_USER_ID" VARCHAR2(32 BYTE), 
	"UPDATE_TIME" DATE, 
	"STATE" NUMBER, 
	"REMARK" VARCHAR2(256 BYTE), 
	"SCRIPT" VARCHAR2(512 BYTE), 
	"AUTORULES_ID" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_AUTORULE"."UUID" IS '����ID';
 
   COMMENT ON COLUMN "QUALITY_AUTORULE"."NAME" IS '�������';
 
   COMMENT ON COLUMN "QUALITY_AUTORULE"."CONTENT" IS '��������';
 
   COMMENT ON COLUMN "QUALITY_AUTORULE"."UPDATE_USER_ID" IS '�������û�ID';
 
   COMMENT ON COLUMN "QUALITY_AUTORULE"."UPDATE_TIME" IS '������ʱ��';
 
   COMMENT ON COLUMN "QUALITY_AUTORULE"."STATE" IS '״̬:0��ʾ���ã�1��ʾ����';
 
   COMMENT ON COLUMN "QUALITY_AUTORULE"."REMARK" IS '��ע';
 
   COMMENT ON COLUMN "QUALITY_AUTORULE"."SCRIPT" IS '�����߼�';
 
   COMMENT ON COLUMN "QUALITY_AUTORULE"."AUTORULES_ID" IS '��������';
--------------------------------------------------------
--  DDL for Table QUALITY_AUTORULES
--------------------------------------------------------

  CREATE TABLE "QUALITY_AUTORULES" 
   (	"UUID" VARCHAR2(32 BYTE), 
	"NAME" VARCHAR2(64 BYTE), 
	"REMARK" VARCHAR2(256 BYTE), 
	"UPDATE_USER_ID" VARCHAR2(32 BYTE), 
	"UPDATE_TIME" DATE, 
	"PRECONDITIONS" VARCHAR2(256 BYTE), 
	"STATE" NUMBER, 
	"SEARCHINFO" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_AUTORULES"."UUID" IS '����ID';
 
   COMMENT ON COLUMN "QUALITY_AUTORULES"."NAME" IS '�Զ��ʼ�������';
 
   COMMENT ON COLUMN "QUALITY_AUTORULES"."REMARK" IS '��ע';
 
   COMMENT ON COLUMN "QUALITY_AUTORULES"."UPDATE_USER_ID" IS '�������û�';
 
   COMMENT ON COLUMN "QUALITY_AUTORULES"."UPDATE_TIME" IS '������ʱ��';
 
   COMMENT ON COLUMN "QUALITY_AUTORULES"."PRECONDITIONS" IS 'Ԥ������';
 
   COMMENT ON COLUMN "QUALITY_AUTORULES"."STATE" IS '״̬��0�ǽ��ã�1������';
 
   COMMENT ON COLUMN "QUALITY_AUTORULES"."SEARCHINFO" IS '���򼯼�������';
--------------------------------------------------------
--  DDL for Table QUALITY_FREE_QUALITY
--------------------------------------------------------

  CREATE TABLE "QUALITY_FREE_QUALITY" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"USER_ID" VARCHAR2(32 CHAR), 
	"REMARK" VARCHAR2(256 CHAR), 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"UPDATE_USER_ID" VARCHAR2(32 CHAR), 
	"UPDATE_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_FREE_QUALITY"."UUID" IS '����';
 
   COMMENT ON COLUMN "QUALITY_FREE_QUALITY"."USER_ID" IS '����û���ʶ';
 
   COMMENT ON COLUMN "QUALITY_FREE_QUALITY"."REMARK" IS '��ע';
 
   COMMENT ON COLUMN "QUALITY_FREE_QUALITY"."START_TIME" IS '��Чʱ��';
 
   COMMENT ON COLUMN "QUALITY_FREE_QUALITY"."END_TIME" IS '����ʱ��';
 
   COMMENT ON COLUMN "QUALITY_FREE_QUALITY"."UPDATE_USER_ID" IS '�������û�';
 
   COMMENT ON COLUMN "QUALITY_FREE_QUALITY"."UPDATE_TIME" IS '����ʱ��';
 
   COMMENT ON TABLE "QUALITY_FREE_QUALITY"  IS '����û���';
--------------------------------------------------------
--  DDL for Table QUALITY_HOT_WORD
--------------------------------------------------------

  CREATE TABLE "QUALITY_HOT_WORD" 
   (	"UUID" VARCHAR2(32 BYTE), 
	"CONTENT" VARCHAR2(64 BYTE), 
	"UPDATE_TIME" DATE, 
	"UPDATE_USER_ID" VARCHAR2(32 BYTE), 
	"STATE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_HOT_WORD"."UUID" IS '����id';
 
   COMMENT ON COLUMN "QUALITY_HOT_WORD"."CONTENT" IS '����';
 
   COMMENT ON COLUMN "QUALITY_HOT_WORD"."UPDATE_TIME" IS '����ʱ��';
 
   COMMENT ON COLUMN "QUALITY_HOT_WORD"."UPDATE_USER_ID" IS '�����û�';
 
   COMMENT ON COLUMN "QUALITY_HOT_WORD"."STATE" IS '״̬  0����ֹ  1������';
--------------------------------------------------------
--  DDL for Table QUALITY_KEYWORD
--------------------------------------------------------

  CREATE TABLE "QUALITY_KEYWORD" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"KEYWORD" VARCHAR2(64 CHAR), 
	"TYPE_ID" VARCHAR2(32 CHAR), 
	"UPDATE_USER_ID" VARCHAR2(32 CHAR), 
	"UPDATE_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_KEYWORD"."UUID" IS '����';
 
   COMMENT ON COLUMN "QUALITY_KEYWORD"."KEYWORD" IS '�ؼ��';
 
   COMMENT ON COLUMN "QUALITY_KEYWORD"."TYPE_ID" IS '�ؼ���������';
 
   COMMENT ON COLUMN "QUALITY_KEYWORD"."UPDATE_USER_ID" IS '��������';
 
   COMMENT ON COLUMN "QUALITY_KEYWORD"."UPDATE_TIME" IS '������ʱ��';
 
   COMMENT ON TABLE "QUALITY_KEYWORD"  IS '�ؼ�ʱ�';
--------------------------------------------------------
--  DDL for Table QUALITY_KEYWORD_TYPE
--------------------------------------------------------

  CREATE TABLE "QUALITY_KEYWORD_TYPE" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"NAME" VARCHAR2(64 CHAR), 
	"COLOR" VARCHAR2(20 CHAR), 
	"REMARK" VARCHAR2(256 BYTE), 
	"UPDATE_USER_ID" VARCHAR2(32 CHAR), 
	"UPDATE_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_KEYWORD_TYPE"."UUID" IS '����';
 
   COMMENT ON COLUMN "QUALITY_KEYWORD_TYPE"."NAME" IS '���';
 
   COMMENT ON COLUMN "QUALITY_KEYWORD_TYPE"."COLOR" IS '��ɫ';
 
   COMMENT ON COLUMN "QUALITY_KEYWORD_TYPE"."REMARK" IS '��ע';
 
   COMMENT ON COLUMN "QUALITY_KEYWORD_TYPE"."UPDATE_USER_ID" IS '��������';
 
   COMMENT ON COLUMN "QUALITY_KEYWORD_TYPE"."UPDATE_TIME" IS '������ʱ��';
 
   COMMENT ON TABLE "QUALITY_KEYWORD_TYPE"  IS '�ؼ������';
--------------------------------------------------------
--  DDL for Table QUALITY_MEMBER_TYPE
--------------------------------------------------------

  CREATE TABLE "QUALITY_MEMBER_TYPE" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"NAME" VARCHAR2(64 CHAR), 
	"CODE" VARCHAR2(256 CHAR), 
	"VALUE_TYPE" NUMBER(*,0), 
	"UPDATE_USER_ID" VARCHAR2(32 CHAR), 
	"UPDATE_TIME" DATE, 
	"ENUM_VALUE" VARCHAR2(512 CHAR), 
	"MIN_VALUE" NUMBER(38,0), 
	"MAX_VALUE" NUMBER(38,0), 
	"NUMBER_TYPE" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_MEMBER_TYPE"."UUID" IS '����';
 
   COMMENT ON COLUMN "QUALITY_MEMBER_TYPE"."NAME" IS '���';
 
   COMMENT ON COLUMN "QUALITY_MEMBER_TYPE"."CODE" IS '������';
 
   COMMENT ON COLUMN "QUALITY_MEMBER_TYPE"."VALUE_TYPE" IS 'ȡֵ���ͣ�0Ϊ��ȷƥ�䣬1Ϊȫ�ļ�����2Ϊ��ֵ���ͣ�3Ϊö������';
 
   COMMENT ON COLUMN "QUALITY_MEMBER_TYPE"."UPDATE_USER_ID" IS '��������';
 
   COMMENT ON COLUMN "QUALITY_MEMBER_TYPE"."UPDATE_TIME" IS '����ʱ��';
 
   COMMENT ON COLUMN "QUALITY_MEMBER_TYPE"."ENUM_VALUE" IS 'ö�����͵�ȡֵ���ö��Ÿ���';
 
   COMMENT ON COLUMN "QUALITY_MEMBER_TYPE"."MIN_VALUE" IS '��ֵ������Сֵ';
 
   COMMENT ON COLUMN "QUALITY_MEMBER_TYPE"."MAX_VALUE" IS '��ֵ���͵����ֵ';
 
   COMMENT ON COLUMN "QUALITY_MEMBER_TYPE"."NUMBER_TYPE" IS '��ֵ����';
 
   COMMENT ON TABLE "QUALITY_MEMBER_TYPE"  IS '�ʼ��������';
--------------------------------------------------------
--  DDL for Table QUALITY_PRECONDITION
--------------------------------------------------------

  CREATE TABLE "QUALITY_PRECONDITION" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"PRECONDITION_TYPE_ID" VARCHAR2(32 CHAR), 
	"RULES_ID" VARCHAR2(32 CHAR), 
	"MAX_VALUE" NUMBER(*,0), 
	"MIN_VALUE" NUMBER(*,0), 
	"EQUAL_VALUE" VARCHAR2(128 CHAR), 
	"NAME" VARCHAR2(32 CHAR), 
	"RULE_ID" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_PRECONDITION"."UUID" IS '����';
 
   COMMENT ON COLUMN "QUALITY_PRECONDITION"."PRECONDITION_TYPE_ID" IS 'Ԥ����������';
 
   COMMENT ON COLUMN "QUALITY_PRECONDITION"."RULES_ID" IS '��������';
 
   COMMENT ON COLUMN "QUALITY_PRECONDITION"."MAX_VALUE" IS '���ֵ';
 
   COMMENT ON COLUMN "QUALITY_PRECONDITION"."MIN_VALUE" IS '��Сֵ';
 
   COMMENT ON COLUMN "QUALITY_PRECONDITION"."EQUAL_VALUE" IS '��ȷֵ';
 
   COMMENT ON COLUMN "QUALITY_PRECONDITION"."NAME" IS '���';
 
   COMMENT ON COLUMN "QUALITY_PRECONDITION"."RULE_ID" IS '��������';
 
   COMMENT ON TABLE "QUALITY_PRECONDITION"  IS '����ǰ������';
--------------------------------------------------------
--  DDL for Table QUALITY_PRECONDITION_TYPE
--------------------------------------------------------

  CREATE TABLE "QUALITY_PRECONDITION_TYPE" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"ENUM_VALUE" VARCHAR2(512 CHAR), 
	"NAME" VARCHAR2(64 CHAR), 
	"CODE" VARCHAR2(256 CHAR), 
	"VALUE_TYPE" NUMBER(*,0), 
	"UPDATE_USER_ID" VARCHAR2(32 CHAR), 
	"UPDATE_TIME" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_PRECONDITION_TYPE"."UUID" IS '����';
 
   COMMENT ON COLUMN "QUALITY_PRECONDITION_TYPE"."ENUM_VALUE" IS 'ö�����͵�ȡֵ���ö��Ÿ�����';
 
   COMMENT ON COLUMN "QUALITY_PRECONDITION_TYPE"."NAME" IS '���';
 
   COMMENT ON COLUMN "QUALITY_PRECONDITION_TYPE"."CODE" IS '������';
 
   COMMENT ON COLUMN "QUALITY_PRECONDITION_TYPE"."VALUE_TYPE" IS 'ȡֵ���ͣ�0Ϊ��ȷƥ�䣬1Ϊģ��ƥ�䣬2Ϊ������ͣ�3Ϊö�����ͣ�4Ϊ����ƥ�䣬-1Ϊϵͳ��ݣ���ʱֻ֧���û��飩';
 
   COMMENT ON COLUMN "QUALITY_PRECONDITION_TYPE"."UPDATE_USER_ID" IS '����޸���';
 
   COMMENT ON COLUMN "QUALITY_PRECONDITION_TYPE"."UPDATE_TIME" IS '�޸�ʱ��';
 
   COMMENT ON TABLE "QUALITY_PRECONDITION_TYPE"  IS '��Ч�������ͱ�';
--------------------------------------------------------
--  DDL for Table QUALITY_RULE
--------------------------------------------------------

  CREATE TABLE "QUALITY_RULE" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"RULES_ID" VARCHAR2(32 CHAR), 
	"RULE_TYPE_ID" VARCHAR2(32 CHAR), 
	"MAX_VALUE" FLOAT(10), 
	"MIN_VALUE" FLOAT(10), 
	"EQUAL_VALUE" VARCHAR2(512 CHAR), 
	"RESULT_TYPE" NUMBER(*,0), 
	"PRECONDITIONS" VARCHAR2(512 CHAR), 
	"NAME" VARCHAR2(64 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_RULE"."UUID" IS '����';
 
   COMMENT ON COLUMN "QUALITY_RULE"."RULES_ID" IS '��������';
 
   COMMENT ON COLUMN "QUALITY_RULE"."RULE_TYPE_ID" IS '��������';
 
   COMMENT ON COLUMN "QUALITY_RULE"."MAX_VALUE" IS '���ֵ';
 
   COMMENT ON COLUMN "QUALITY_RULE"."MIN_VALUE" IS '��Сֵ';
 
   COMMENT ON COLUMN "QUALITY_RULE"."EQUAL_VALUE" IS '��ȷֵ�����ֵ�ö��Ÿ���';
 
   COMMENT ON COLUMN "QUALITY_RULE"."RESULT_TYPE" IS '�ʼ������͡���ϴ˹��������£�0Ϊ��1Ϊ���棬2ΪΥ�棬3Ϊ�ش�Υ��';
 
   COMMENT ON COLUMN "QUALITY_RULE"."PRECONDITIONS" IS 'Ԥ������';
 
   COMMENT ON COLUMN "QUALITY_RULE"."NAME" IS '���';
 
   COMMENT ON TABLE "QUALITY_RULE"  IS '�ʼ����';
--------------------------------------------------------
--  DDL for Table QUALITY_RULE_TYPE
--------------------------------------------------------

  CREATE TABLE "QUALITY_RULE_TYPE" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"NAME" VARCHAR2(64 CHAR), 
	"CODE" VARCHAR2(256 CHAR), 
	"VALUE_TYPE" NUMBER(*,0), 
	"UPDATE_USER_ID" VARCHAR2(32 CHAR), 
	"UPDATE_TIME" DATE, 
	"ENUM_VALUE" VARCHAR2(512 CHAR), 
	"MIN_VALUE" NUMBER(38,0), 
	"MAX_VALUE" NUMBER(38,0), 
	"NUMBER_TYPE" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_RULE_TYPE"."UUID" IS '����';
 
   COMMENT ON COLUMN "QUALITY_RULE_TYPE"."NAME" IS '���';
 
   COMMENT ON COLUMN "QUALITY_RULE_TYPE"."CODE" IS '������';
 
   COMMENT ON COLUMN "QUALITY_RULE_TYPE"."VALUE_TYPE" IS 'ȡֵ���ͣ�0Ϊ��ȷƥ�䣬1Ϊȫ�ļ�����2Ϊ��ֵ���ͣ�3Ϊö������';
 
   COMMENT ON COLUMN "QUALITY_RULE_TYPE"."UPDATE_USER_ID" IS '��������';
 
   COMMENT ON COLUMN "QUALITY_RULE_TYPE"."UPDATE_TIME" IS '����ʱ��';
 
   COMMENT ON COLUMN "QUALITY_RULE_TYPE"."ENUM_VALUE" IS 'ö�����͵�ȡֵ���ö��Ÿ���';
 
   COMMENT ON COLUMN "QUALITY_RULE_TYPE"."MIN_VALUE" IS '��ֵ������Сֵ';
 
   COMMENT ON COLUMN "QUALITY_RULE_TYPE"."MAX_VALUE" IS '��ֵ���͵����ֵ';
 
   COMMENT ON COLUMN "QUALITY_RULE_TYPE"."NUMBER_TYPE" IS '��ֵ����';
 
   COMMENT ON TABLE "QUALITY_RULE_TYPE"  IS '�ʼ��������';
--------------------------------------------------------
--  DDL for Table QUALITY_RULES
--------------------------------------------------------

  CREATE TABLE "QUALITY_RULES" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"NAME" VARCHAR2(64 CHAR), 
	"REMARK" VARCHAR2(128 CHAR), 
	"STATE" NUMBER(*,0), 
	"UPDATE_USER_ID" VARCHAR2(32 CHAR), 
	"UPDATE_TIME" DATE, 
	"PRECONDITIONS" VARCHAR2(1024 CHAR), 
	"RULES_TYPE_ID" VARCHAR2(32 CHAR), 
	"START_TIME" DATE, 
	"END_TIME" DATE, 
	"USER_GROUP_SET" VARCHAR2(1024 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_RULES"."UUID" IS '����';
 
   COMMENT ON COLUMN "QUALITY_RULES"."NAME" IS '���';
 
   COMMENT ON COLUMN "QUALITY_RULES"."REMARK" IS '��ע';
 
   COMMENT ON COLUMN "QUALITY_RULES"."STATE" IS '�Ƿ���Ч��0����Ч��1��Ч';
 
   COMMENT ON COLUMN "QUALITY_RULES"."UPDATE_USER_ID" IS '��������';
 
   COMMENT ON COLUMN "QUALITY_RULES"."UPDATE_TIME" IS '����ʱ��';
 
   COMMENT ON COLUMN "QUALITY_RULES"."PRECONDITIONS" IS 'Ԥ������';
 
   COMMENT ON COLUMN "QUALITY_RULES"."RULES_TYPE_ID" IS '��������';
 
   COMMENT ON COLUMN "QUALITY_RULES"."START_TIME" IS '��Ч��ʼʱ��';
 
   COMMENT ON COLUMN "QUALITY_RULES"."END_TIME" IS '��Ч����ʱ��';
 
   COMMENT ON COLUMN "QUALITY_RULES"."USER_GROUP_SET" IS '��Ч�û��鼯��';
 
   COMMENT ON TABLE "QUALITY_RULES"  IS '�ʼ����';
--------------------------------------------------------
--  DDL for Table QUALITY_RULES_TYPE
--------------------------------------------------------

  CREATE TABLE "QUALITY_RULES_TYPE" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"NAME" VARCHAR2(64 CHAR), 
	"REMARK" VARCHAR2(128 CHAR), 
	"UPDATE_USER_ID" VARCHAR2(32 CHAR), 
	"UPDATE_TIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_RULES_TYPE"."UUID" IS '����';
 
   COMMENT ON COLUMN "QUALITY_RULES_TYPE"."NAME" IS '���';
 
   COMMENT ON COLUMN "QUALITY_RULES_TYPE"."REMARK" IS '��ע';
 
   COMMENT ON COLUMN "QUALITY_RULES_TYPE"."UPDATE_USER_ID" IS '��������';
 
   COMMENT ON COLUMN "QUALITY_RULES_TYPE"."UPDATE_TIME" IS '������ʱ��';
 
   COMMENT ON TABLE "QUALITY_RULES_TYPE"  IS '�ʼ��������';
--------------------------------------------------------
--  DDL for Table QUALITY_SEARCH_INFO
--------------------------------------------------------

  CREATE TABLE "QUALITY_SEARCH_INFO" 
   (	"UUID" VARCHAR2(32 BYTE), 
	"USER_ID" VARCHAR2(32 BYTE), 
	"CREATE_TIME" DATE, 
	"SEARCH_INFO" VARCHAR2(2048 BYTE), 
	"NAME" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_SEARCH_INFO"."UUID" IS '����';
 
   COMMENT ON COLUMN "QUALITY_SEARCH_INFO"."USER_ID" IS '�����û�ID';
 
   COMMENT ON COLUMN "QUALITY_SEARCH_INFO"."CREATE_TIME" IS '����ʱ��';
 
   COMMENT ON COLUMN "QUALITY_SEARCH_INFO"."SEARCH_INFO" IS '������Ϣ';
 
   COMMENT ON COLUMN "QUALITY_SEARCH_INFO"."NAME" IS '�������';
--------------------------------------------------------
--  DDL for Table QUALITY_STANDARD_SPEECH
--------------------------------------------------------

  CREATE TABLE "QUALITY_STANDARD_SPEECH" 
   (	"UUID" VARCHAR2(32 BYTE), 
	"NAME" VARCHAR2(64 BYTE), 
	"UPDATE_USER_ID" VARCHAR2(32 BYTE), 
	"CONTENT" VARCHAR2(4000 BYTE), 
	"STATE" NUMBER, 
	"UPDATE_TIME" TIMESTAMP (6), 
	"THRESHOLD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "QUALITY_STANDARD_SPEECH"."UUID" IS '����ID';
 
   COMMENT ON COLUMN "QUALITY_STANDARD_SPEECH"."NAME" IS '��׼�������';
 
   COMMENT ON COLUMN "QUALITY_STANDARD_SPEECH"."UPDATE_USER_ID" IS '�༭�û�ID';
 
   COMMENT ON COLUMN "QUALITY_STANDARD_SPEECH"."CONTENT" IS '��׼��������';
 
   COMMENT ON COLUMN "QUALITY_STANDARD_SPEECH"."STATE" IS '״̬  0����ֹ   1������';
 
   COMMENT ON COLUMN "QUALITY_STANDARD_SPEECH"."UPDATE_TIME" IS '�༭ʱ��';
 
   COMMENT ON COLUMN "QUALITY_STANDARD_SPEECH"."THRESHOLD" IS '��ֵ';
--------------------------------------------------------
--  DDL for Table SYS_MENU
--------------------------------------------------------

  CREATE TABLE "SYS_MENU" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"NAME" VARCHAR2(64 CHAR), 
	"URL" VARCHAR2(256 CHAR), 
	"ORDER_NUM" NUMBER(*,0) DEFAULT 0, 
	"STATE" NUMBER(*,0) DEFAULT 1, 
	"PARENT_ID" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SYS_OPERATION_LOG
--------------------------------------------------------

  CREATE TABLE "SYS_OPERATION_LOG" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"USER_ID" VARCHAR2(32 CHAR), 
	"OPERATION_MENU" VARCHAR2(64 CHAR), 
	"OPERATION_TYPE" VARCHAR2(32 CHAR), 
	"OPERATION_DATA" VARCHAR2(100 CHAR), 
	"OPERATION_TIME" DATE, 
	"USER_NAME" VARCHAR2(64 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "SYS_OPERATION_LOG"."UUID" IS '����';
 
   COMMENT ON COLUMN "SYS_OPERATION_LOG"."USER_ID" IS '�����û�';
 
   COMMENT ON COLUMN "SYS_OPERATION_LOG"."OPERATION_MENU" IS '�����˵�����';
 
   COMMENT ON COLUMN "SYS_OPERATION_LOG"."OPERATION_TYPE" IS '�������ͣ���ɾ��';
 
   COMMENT ON COLUMN "SYS_OPERATION_LOG"."OPERATION_DATA" IS '�������';
 
   COMMENT ON COLUMN "SYS_OPERATION_LOG"."OPERATION_TIME" IS '����ʱ��';
 
   COMMENT ON COLUMN "SYS_OPERATION_LOG"."USER_NAME" IS '�û����';
 
   COMMENT ON TABLE "SYS_OPERATION_LOG"  IS '������¼��';
--------------------------------------------------------
--  DDL for Table SYS_PARAM
--------------------------------------------------------

  CREATE TABLE "SYS_PARAM" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"NAME" VARCHAR2(64 CHAR), 
	"VALUE" VARCHAR2(256 CHAR), 
	"REMARK" VARCHAR2(128 CHAR), 
	"TYPE" NUMBER(*,0), 
	"REGEXP" VARCHAR2(400 CHAR), 
	"ERRORMSG" VARCHAR2(400 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "SYS_PARAM"."UUID" IS '����';
 
   COMMENT ON COLUMN "SYS_PARAM"."NAME" IS '���';
 
   COMMENT ON COLUMN "SYS_PARAM"."VALUE" IS '����ֵ';
 
   COMMENT ON COLUMN "SYS_PARAM"."REMARK" IS '��ע';
 
   COMMENT ON COLUMN "SYS_PARAM"."TYPE" IS '�������͡�0Ϊasr�������1ΪCTI�ӿڲ���2Ϊ�ʼ��������4Ϊ�����������5Ϊ�������';
 
   COMMENT ON COLUMN "SYS_PARAM"."REGEXP" IS '����ֵ����У��';
 
   COMMENT ON COLUMN "SYS_PARAM"."ERRORMSG" IS '����У�������ʾ';
 
   COMMENT ON TABLE "SYS_PARAM"  IS 'ϵͳ�����';
--------------------------------------------------------
--  DDL for Table SYS_ROLE
--------------------------------------------------------

  CREATE TABLE "SYS_ROLE" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"NAME" VARCHAR2(64 CHAR), 
	"REMARK" VARCHAR2(128 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "SYS_ROLE"."UUID" IS '����';
 
   COMMENT ON COLUMN "SYS_ROLE"."NAME" IS '���';
 
   COMMENT ON COLUMN "SYS_ROLE"."REMARK" IS '��ע';
 
   COMMENT ON TABLE "SYS_ROLE"  IS '��ɫ��';
--------------------------------------------------------
--  DDL for Table SYS_ROLE_MENU_RELATION
--------------------------------------------------------

  CREATE TABLE "SYS_ROLE_MENU_RELATION" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"ROLE_ID" VARCHAR2(32 CHAR), 
	"MENU_ID" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "SYS_ROLE_MENU_RELATION"."UUID" IS '����';
 
   COMMENT ON COLUMN "SYS_ROLE_MENU_RELATION"."ROLE_ID" IS '��ɫ';
 
   COMMENT ON COLUMN "SYS_ROLE_MENU_RELATION"."MENU_ID" IS '�˵�';
 
   COMMENT ON TABLE "SYS_ROLE_MENU_RELATION"  IS '��ɫ�˵���ϵ��';
--------------------------------------------------------
--  DDL for Table SYS_USER
--------------------------------------------------------

  CREATE TABLE "SYS_USER" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"NAME" VARCHAR2(64 CHAR), 
	"LOGIN_NAME" VARCHAR2(64 CHAR), 
	"PASSWORD" VARCHAR2(128 CHAR), 
	"USER_GROUP_ID" VARCHAR2(32 CHAR), 
	"UPDATE_USER_ID" VARCHAR2(32 CHAR), 
	"UPDATE_TIME" DATE, 
	"STATE" NUMBER(*,0), 
	"REMARK" VARCHAR2(128 CHAR), 
	"ISDELETE" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "SYS_USER"."UUID" IS '����';
 
   COMMENT ON COLUMN "SYS_USER"."NAME" IS '���';
 
   COMMENT ON COLUMN "SYS_USER"."LOGIN_NAME" IS '��½���';
 
   COMMENT ON COLUMN "SYS_USER"."PASSWORD" IS '����';
 
   COMMENT ON COLUMN "SYS_USER"."USER_GROUP_ID" IS '�û���';
 
   COMMENT ON COLUMN "SYS_USER"."UPDATE_USER_ID" IS '�������û�';
 
   COMMENT ON COLUMN "SYS_USER"."UPDATE_TIME" IS '������ʱ��';
 
   COMMENT ON COLUMN "SYS_USER"."STATE" IS '�Ƿ����ã�1Ϊ���ã�0Ϊͣ��';
 
   COMMENT ON COLUMN "SYS_USER"."REMARK" IS '��ע';
 
   COMMENT ON COLUMN "SYS_USER"."ISDELETE" IS '�Ƿ���ɾ��1�û���ɾ��0δɾ��';
--------------------------------------------------------
--  DDL for Table SYS_USER_GROUP
--------------------------------------------------------

  CREATE TABLE "SYS_USER_GROUP" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"NAME" VARCHAR2(64 CHAR), 
	"UPDATE_USER_ID" VARCHAR2(32 CHAR), 
	"UPDATE_TIME" DATE, 
	"REMARK" VARCHAR2(128 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "SYS_USER_GROUP"."UUID" IS '����';
 
   COMMENT ON COLUMN "SYS_USER_GROUP"."NAME" IS '���';
 
   COMMENT ON COLUMN "SYS_USER_GROUP"."UPDATE_USER_ID" IS '�������û�';
 
   COMMENT ON COLUMN "SYS_USER_GROUP"."UPDATE_TIME" IS '������ʱ��';
 
   COMMENT ON COLUMN "SYS_USER_GROUP"."REMARK" IS '��ע';
 
   COMMENT ON TABLE "SYS_USER_GROUP"  IS '�û����';
--------------------------------------------------------
--  DDL for Table SYS_USER_ROLE_RELATION
--------------------------------------------------------

  CREATE TABLE "SYS_USER_ROLE_RELATION" 
   (	"USER_ID" VARCHAR2(32 CHAR), 
	"ROLE_ID" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "SYS_USER_ROLE_RELATION"."USER_ID" IS '�û�';
 
   COMMENT ON COLUMN "SYS_USER_ROLE_RELATION"."ROLE_ID" IS '��ɫ';
 
   COMMENT ON TABLE "SYS_USER_ROLE_RELATION"  IS '�û���ɫ��ϵ��';
--------------------------------------------------------
--  DDL for Table SYS_VERSION
--------------------------------------------------------

  CREATE TABLE "SYS_VERSION" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"VERSION" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "SYS_VERSION"."UUID" IS '����';
 
   COMMENT ON COLUMN "SYS_VERSION"."VERSION" IS '�汾';
 
   COMMENT ON TABLE "SYS_VERSION"  IS '�汾';
--------------------------------------------------------
--  DDL for Table VOICE_ANALYSIS_DATA
--------------------------------------------------------

  CREATE TABLE "VOICE_ANALYSIS_DATA" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"ANALYSIS_DATA" LONG
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "VOICE_ANALYSIS_DATA"."UUID" IS '����';
 
   COMMENT ON COLUMN "VOICE_ANALYSIS_DATA"."ANALYSIS_DATA" IS '�ʼ���';
 
   COMMENT ON TABLE "VOICE_ANALYSIS_DATA"  IS '�ʼ����';
--------------------------------------------------------
--  DDL for Table VOICE_DATA
--------------------------------------------------------

  CREATE TABLE "VOICE_DATA" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"TRANS_DATA_ID" VARCHAR2(32 CHAR), 
	"RELATE_DATA_ID" VARCHAR2(32 CHAR), 
	"QUALITY_DATA_ID" VARCHAR2(32 CHAR), 
	"ANALYSIS_DATA_ID" VARCHAR2(32 CHAR), 
	"ONLINE_DATA_ID" VARCHAR2(32 CHAR), 
	"MANUAL_DATA_ID" VARCHAR2(32 CHAR), 
	"CREATIME" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "VOICE_DATA"."UUID" IS '����';
 
   COMMENT ON COLUMN "VOICE_DATA"."TRANS_DATA_ID" IS 'תд���';
 
   COMMENT ON COLUMN "VOICE_DATA"."RELATE_DATA_ID" IS '��·���';
 
   COMMENT ON COLUMN "VOICE_DATA"."QUALITY_DATA_ID" IS '�Զ��ʼ���';
 
   COMMENT ON COLUMN "VOICE_DATA"."ANALYSIS_DATA_ID" IS '�������';
 
   COMMENT ON COLUMN "VOICE_DATA"."ONLINE_DATA_ID" IS '����ģʽ���';
 
   COMMENT ON COLUMN "VOICE_DATA"."MANUAL_DATA_ID" IS '�˹��ʼ���';
 
   COMMENT ON TABLE "VOICE_DATA"  IS '¼����';
--------------------------------------------------------
--  DDL for Table VOICE_MANUAL_DATA
--------------------------------------------------------

  CREATE TABLE "VOICE_MANUAL_DATA" 
   (	"UUID" VARCHAR2(32 BYTE), 
	"QUALITY_DATA" LONG
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "VOICE_MANUAL_DATA"."QUALITY_DATA" IS '�ʼ���';
--------------------------------------------------------
--  DDL for Table VOICE_ONLINE_DATA
--------------------------------------------------------

  CREATE TABLE "VOICE_ONLINE_DATA" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"ONLINE_DATA" LONG
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "VOICE_ONLINE_DATA"."UUID" IS '����';
 
   COMMENT ON COLUMN "VOICE_ONLINE_DATA"."ONLINE_DATA" IS '�������';
 
   COMMENT ON TABLE "VOICE_ONLINE_DATA"  IS '����ģʽ���';
--------------------------------------------------------
--  DDL for Table VOICE_QUALITY_DATA
--------------------------------------------------------

  CREATE TABLE "VOICE_QUALITY_DATA" 
   (	"UUID" VARCHAR2(32 BYTE), 
	"QUALITY_DATA" LONG
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "VOICE_QUALITY_DATA"."QUALITY_DATA" IS '�ʼ���';
 
   COMMENT ON TABLE "VOICE_QUALITY_DATA"  IS '�ʼ����';
--------------------------------------------------------
--  DDL for Table VOICE_RELATE_DATA
--------------------------------------------------------

  CREATE TABLE "VOICE_RELATE_DATA" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"RELATE_DATA" LONG
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "VOICE_RELATE_DATA"."UUID" IS '����';
 
   COMMENT ON COLUMN "VOICE_RELATE_DATA"."RELATE_DATA" IS '��·���';
 
   COMMENT ON TABLE "VOICE_RELATE_DATA"  IS '��·��ݱ�';
--------------------------------------------------------
--  DDL for Table VOICE_TRANS_DATA
--------------------------------------------------------

  CREATE TABLE "VOICE_TRANS_DATA" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"TEXT" LONG
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "VOICE_TRANS_DATA"."UUID" IS '����';
 
   COMMENT ON COLUMN "VOICE_TRANS_DATA"."TEXT" IS 'תд����';
 
   COMMENT ON TABLE "VOICE_TRANS_DATA"  IS 'תд���ݱ�';
--------------------------------------------------------
--  DDL for Table VTS_OPERATION_LOG
--------------------------------------------------------

  CREATE TABLE "VTS_OPERATION_LOG" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"IP" VARCHAR2(64 CHAR), 
	"OPERATION_TYPE" VARCHAR2(32 CHAR), 
	"NUM" NUMBER(11,0), 
	"FLAG" CHAR(1 CHAR), 
	"OPERATION_TIME" DATE, 
	"CALL_CENTER" CHAR(1 CHAR), 
	"TASK_NO" VARCHAR2(32 CHAR), 
	"MESSAGE_NO" VARCHAR2(64 CHAR), 
	"MESSAGE" VARCHAR2(4000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "VTS_OPERATION_LOG"."UUID" IS '����id';
 
   COMMENT ON COLUMN "VTS_OPERATION_LOG"."IP" IS '����IP';
 
   COMMENT ON COLUMN "VTS_OPERATION_LOG"."OPERATION_TYPE" IS '��������
scan:��ʱɨ������
trans:תд����
transBusy:����תд��ȥתд����busy��δ����תд������
callback:תд����ص�
send:תд����ϱ�
mail:�ʼ��澯';
 
   COMMENT ON COLUMN "VTS_OPERATION_LOG"."NUM" IS '��������ļ�����';
 
   COMMENT ON COLUMN "VTS_OPERATION_LOG"."FLAG" IS '�Ƿ�ɹ� 1�ɹ�0ʧ��';
 
   COMMENT ON COLUMN "VTS_OPERATION_LOG"."OPERATION_TIME" IS '����ִ��ʱ��';
 
   COMMENT ON COLUMN "VTS_OPERATION_LOG"."CALL_CENTER" IS 'N�����ģ�S������';
 
   COMMENT ON COLUMN "VTS_OPERATION_LOG"."TASK_NO" IS '�����������';
 
   COMMENT ON COLUMN "VTS_OPERATION_LOG"."MESSAGE_NO" IS '��ϢΨһ���';
 
   COMMENT ON COLUMN "VTS_OPERATION_LOG"."MESSAGE" IS '��Ϣ����';
--------------------------------------------------------
--  DDL for Table VTS_SYS_PARAM
--------------------------------------------------------

  CREATE TABLE "VTS_SYS_PARAM" 
   (	"UUID" VARCHAR2(32 CHAR), 
	"NAME" VARCHAR2(64 CHAR), 
	"VALUE" VARCHAR2(256 CHAR), 
	"REMARK" VARCHAR2(128 CHAR), 
	"REGEX" VARCHAR2(128 CHAR), 
	"MAX_VALUE" NUMBER(*,0), 
	"MIN_VALUE" NUMBER(*,0), 
	"TYPE" NUMBER(*,0), 
	"CREAT_TIME" DATE, 
	"VALUE_TYPE" NUMBER(*,0), 
	"MAX_FLOAT_VALUE" NUMBER(*,2), 
	"MIN_FLOAT_VALUE" NUMBER(*,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "VTS_SYS_PARAM"."UUID" IS '����uuid';
 
   COMMENT ON COLUMN "VTS_SYS_PARAM"."NAME" IS 'ϵͳ�������';
 
   COMMENT ON COLUMN "VTS_SYS_PARAM"."VALUE" IS 'ϵͳ����ֵ';
 
   COMMENT ON COLUMN "VTS_SYS_PARAM"."REMARK" IS '��ע';
 
   COMMENT ON COLUMN "VTS_SYS_PARAM"."REGEX" IS '����ƥ��';
 
   COMMENT ON COLUMN "VTS_SYS_PARAM"."MAX_VALUE" IS '���ֵ';
 
   COMMENT ON COLUMN "VTS_SYS_PARAM"."MIN_VALUE" IS '��Сֵ';
 
   COMMENT ON COLUMN "VTS_SYS_PARAM"."TYPE" IS '�������͡�0Ϊasr�������1ΪCTI�ӿڲ���2Ϊ�ʼ��������4Ϊ�����������5Ϊ�������';
 
   COMMENT ON COLUMN "VTS_SYS_PARAM"."CREAT_TIME" IS 'ϵͳ�������ʱ��';
 
   COMMENT ON COLUMN "VTS_SYS_PARAM"."VALUE_TYPE" IS '����ֵ�������';
 
   COMMENT ON COLUMN "VTS_SYS_PARAM"."MAX_FLOAT_VALUE" IS '��󸡵���ֵ';
 
   COMMENT ON COLUMN "VTS_SYS_PARAM"."MIN_FLOAT_VALUE" IS '��С������ֵ';
--------------------------------------------------------
--  DDL for Index TABLE1_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "TABLE1_PK1" ON "QUALITY_ARTIFICAL_ITEM" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUALITY_AUTO_LEXICON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUALITY_AUTO_LEXICON_PK" ON "QUALITY_AUTOLEXICON" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUALITY_AUTOLOGIC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUALITY_AUTOLOGIC_PK" ON "QUALITY_AUTOLOGIC" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUALITY_AUTO_PHRASE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUALITY_AUTO_PHRASE_PK" ON "QUALITY_AUTOPHRASE" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUALITY_AUTORULES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUALITY_AUTORULES_PK" ON "QUALITY_AUTORULES" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TABLE1_PK" ON "QUALITY_FREE_QUALITY" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUALITY_HOT_WORD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUALITY_HOT_WORD_PK" ON "QUALITY_HOT_WORD" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUALITY_KEYWORD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUALITY_KEYWORD_PK" ON "QUALITY_KEYWORD" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUALITY_KEYWORD_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUALITY_KEYWORD_TYPE_PK" ON "QUALITY_KEYWORD_TYPE" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUALITY_ROLE_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUALITY_ROLE_TYPE_PK" ON "QUALITY_MEMBER_TYPE" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUALITY_RULE_PRECONDITION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUALITY_RULE_PRECONDITION_PK" ON "QUALITY_PRECONDITION" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUALITY_RUE_PRECONDITION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUALITY_RUE_PRECONDITION_PK" ON "QUALITY_PRECONDITION_TYPE" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUALITY_RULE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUALITY_RULE_PK" ON "QUALITY_RULE" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUALITY_RULE_INDEX1
--------------------------------------------------------

  CREATE INDEX "QUALITY_RULE_INDEX1" ON "QUALITY_RULE" ("RULES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUALITY_ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUALITY_ROLES_PK" ON "QUALITY_RULES" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FORM_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FORM_TYPE_PK" ON "QUALITY_RULES_TYPE" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUALITY_SEARCH_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUALITY_SEARCH_INFO_PK" ON "QUALITY_SEARCH_INFO" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index QUALITY_STANDARD_SPEECH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "QUALITY_STANDARD_SPEECH_PK" ON "QUALITY_STANDARD_SPEECH" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_OPERATION_LOG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_OPERATION_LOG_PK" ON "SYS_OPERATION_LOG" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_OPERATION_LOG_INDEX1
--------------------------------------------------------

  CREATE INDEX "SYS_OPERATION_LOG_INDEX1" ON "SYS_OPERATION_LOG" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_OPERATION_LOG_INDEX2
--------------------------------------------------------

  CREATE INDEX "SYS_OPERATION_LOG_INDEX2" ON "SYS_OPERATION_LOG" ("OPERATION_MENU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_OPERATION_LOG_INDEX3
--------------------------------------------------------

  CREATE INDEX "SYS_OPERATION_LOG_INDEX3" ON "SYS_OPERATION_LOG" ("OPERATION_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_OPERATION_LOG_INDEX4
--------------------------------------------------------

  CREATE INDEX "SYS_OPERATION_LOG_INDEX4" ON "SYS_OPERATION_LOG" ("OPERATION_DATA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_OPERATION_LOG_INDEX5
--------------------------------------------------------

  CREATE INDEX "SYS_OPERATION_LOG_INDEX5" ON "SYS_OPERATION_LOG" ("OPERATION_TIME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_PARAM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_PARAM_PK" ON "SYS_PARAM" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_ROLE_PK" ON "SYS_ROLE" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_ROLE_MENU_RELATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_ROLE_MENU_RELATION_PK" ON "SYS_ROLE_MENU_RELATION" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SAP_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SAP_USER_PK" ON "SYS_USER" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_USER_GROUP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_USER_GROUP_PK" ON "SYS_USER_GROUP" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_USER_ROLE_RELATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_USER_ROLE_RELATION_PK" ON "SYS_USER_ROLE_RELATION" ("USER_ID", "ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_VERSION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_VERSION_PK" ON "SYS_VERSION" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VOICE_ANALYSIS_DATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VOICE_ANALYSIS_DATA_PK" ON "VOICE_ANALYSIS_DATA" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VOICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VOICE_PK" ON "VOICE_DATA" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VOICE_MANUAL_DATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VOICE_MANUAL_DATA_PK" ON "VOICE_MANUAL_DATA" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VOICE_ONLINE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VOICE_ONLINE_PK" ON "VOICE_ONLINE_DATA" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VOICE_QUALITY_DATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VOICE_QUALITY_DATA_PK" ON "VOICE_QUALITY_DATA" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VOICE_RELATE_DATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VOICE_RELATE_DATA_PK" ON "VOICE_RELATE_DATA" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VOICE_TRANS_DATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VOICE_TRANS_DATA_PK" ON "VOICE_TRANS_DATA" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VTS_OPERATION_LOG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VTS_OPERATION_LOG_PK" ON "VTS_OPERATION_LOG" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index VTS_SYS_PARAM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VTS_SYS_PARAM_PK" ON "VTS_SYS_PARAM" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table QUALITY_ARTIFICAL_ITEM
--------------------------------------------------------

  ALTER TABLE "QUALITY_ARTIFICAL_ITEM" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "QUALITY_ARTIFICAL_ITEM" ADD CONSTRAINT "TABLE1_PK1" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QUALITY_AUTOLEXICON
--------------------------------------------------------

  ALTER TABLE "QUALITY_AUTOLEXICON" ADD CONSTRAINT "QUALITY_AUTO_LEXICON_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "QUALITY_AUTOLEXICON" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUALITY_AUTOLOGIC
--------------------------------------------------------

  ALTER TABLE "QUALITY_AUTOLOGIC" ADD CONSTRAINT "QUALITY_AUTOLOGIC_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "QUALITY_AUTOLOGIC" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUALITY_AUTOPHRASE
--------------------------------------------------------

  ALTER TABLE "QUALITY_AUTOPHRASE" ADD CONSTRAINT "QUALITY_AUTO_PHRASE_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "QUALITY_AUTOPHRASE" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUALITY_AUTORULE
--------------------------------------------------------

  ALTER TABLE "QUALITY_AUTORULE" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUALITY_AUTORULES
--------------------------------------------------------

  ALTER TABLE "QUALITY_AUTORULES" ADD CONSTRAINT "QUALITY_AUTORULES_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "QUALITY_AUTORULES" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUALITY_FREE_QUALITY
--------------------------------------------------------

  ALTER TABLE "QUALITY_FREE_QUALITY" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "QUALITY_FREE_QUALITY" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "QUALITY_FREE_QUALITY" MODIFY ("UPDATE_USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "QUALITY_FREE_QUALITY" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QUALITY_HOT_WORD
--------------------------------------------------------

  ALTER TABLE "QUALITY_HOT_WORD" ADD CONSTRAINT "QUALITY_HOT_WORD_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "QUALITY_HOT_WORD" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUALITY_KEYWORD
--------------------------------------------------------

  ALTER TABLE "QUALITY_KEYWORD" ADD CONSTRAINT "QUALITY_KEYWORD_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "QUALITY_KEYWORD" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUALITY_KEYWORD_TYPE
--------------------------------------------------------

  ALTER TABLE "QUALITY_KEYWORD_TYPE" ADD CONSTRAINT "QUALITY_KEYWORD_TYPE_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "QUALITY_KEYWORD_TYPE" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUALITY_MEMBER_TYPE
--------------------------------------------------------

  ALTER TABLE "QUALITY_MEMBER_TYPE" ADD CONSTRAINT "QUALITY_ROLE_TYPE_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "QUALITY_MEMBER_TYPE" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUALITY_PRECONDITION
--------------------------------------------------------

  ALTER TABLE "QUALITY_PRECONDITION" ADD CONSTRAINT "QUALITY_RULE_PRECONDITION_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "QUALITY_PRECONDITION" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUALITY_PRECONDITION_TYPE
--------------------------------------------------------

  ALTER TABLE "QUALITY_PRECONDITION_TYPE" ADD CONSTRAINT "QUALITY_RUE_PRECONDITION_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "QUALITY_PRECONDITION_TYPE" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUALITY_RULE
--------------------------------------------------------

  ALTER TABLE "QUALITY_RULE" ADD CONSTRAINT "QUALITY_RULE_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "QUALITY_RULE" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUALITY_RULES
--------------------------------------------------------

  ALTER TABLE "QUALITY_RULES" ADD CONSTRAINT "QUALITY_ROLES_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "QUALITY_RULES" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUALITY_RULES_TYPE
--------------------------------------------------------

  ALTER TABLE "QUALITY_RULES_TYPE" ADD CONSTRAINT "FORM_TYPE_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "QUALITY_RULES_TYPE" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUALITY_SEARCH_INFO
--------------------------------------------------------

  ALTER TABLE "QUALITY_SEARCH_INFO" ADD CONSTRAINT "QUALITY_SEARCH_INFO_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "QUALITY_SEARCH_INFO" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QUALITY_STANDARD_SPEECH
--------------------------------------------------------

  ALTER TABLE "QUALITY_STANDARD_SPEECH" ADD CONSTRAINT "QUALITY_STANDARD_SPEECH_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "QUALITY_STANDARD_SPEECH" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_OPERATION_LOG
--------------------------------------------------------

  ALTER TABLE "SYS_OPERATION_LOG" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "SYS_OPERATION_LOG" ADD CONSTRAINT "SYS_OPERATION_LOG_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SYS_PARAM
--------------------------------------------------------

  ALTER TABLE "SYS_PARAM" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "SYS_PARAM" ADD CONSTRAINT "SYS_PARAM_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SYS_ROLE
--------------------------------------------------------

  ALTER TABLE "SYS_ROLE" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "SYS_ROLE" ADD CONSTRAINT "SYS_ROLE_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SYS_ROLE_MENU_RELATION
--------------------------------------------------------

  ALTER TABLE "SYS_ROLE_MENU_RELATION" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "SYS_ROLE_MENU_RELATION" ADD CONSTRAINT "SYS_ROLE_MENU_RELATION_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SYS_USER
--------------------------------------------------------

  ALTER TABLE "SYS_USER" ADD CONSTRAINT "SAP_USER_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SYS_USER" MODIFY ("UUID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SYS_USER_GROUP
--------------------------------------------------------

  ALTER TABLE "SYS_USER_GROUP" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "SYS_USER_GROUP" ADD CONSTRAINT "SYS_USER_GROUP_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SYS_USER_ROLE_RELATION
--------------------------------------------------------

  ALTER TABLE "SYS_USER_ROLE_RELATION" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYS_USER_ROLE_RELATION" MODIFY ("ROLE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYS_USER_ROLE_RELATION" ADD CONSTRAINT "SYS_USER_ROLE_RELATION_PK" PRIMARY KEY ("USER_ID", "ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SYS_VERSION
--------------------------------------------------------

  ALTER TABLE "SYS_VERSION" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "SYS_VERSION" ADD CONSTRAINT "SYS_VERSION_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VOICE_ANALYSIS_DATA
--------------------------------------------------------

  ALTER TABLE "VOICE_ANALYSIS_DATA" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "VOICE_ANALYSIS_DATA" ADD CONSTRAINT "VOICE_ANALYSIS_DATA_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VOICE_DATA
--------------------------------------------------------

  ALTER TABLE "VOICE_DATA" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "VOICE_DATA" ADD CONSTRAINT "VOICE_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VOICE_MANUAL_DATA
--------------------------------------------------------

  ALTER TABLE "VOICE_MANUAL_DATA" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "VOICE_MANUAL_DATA" ADD CONSTRAINT "VOICE_MANUAL_DATA_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VOICE_ONLINE_DATA
--------------------------------------------------------

  ALTER TABLE "VOICE_ONLINE_DATA" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "VOICE_ONLINE_DATA" ADD CONSTRAINT "VOICE_ONLINE_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VOICE_QUALITY_DATA
--------------------------------------------------------

  ALTER TABLE "VOICE_QUALITY_DATA" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "VOICE_QUALITY_DATA" ADD CONSTRAINT "VOICE_QUALITY_DATA_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VOICE_RELATE_DATA
--------------------------------------------------------

  ALTER TABLE "VOICE_RELATE_DATA" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "VOICE_RELATE_DATA" ADD CONSTRAINT "VOICE_RELATE_DATA_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VOICE_TRANS_DATA
--------------------------------------------------------

  ALTER TABLE "VOICE_TRANS_DATA" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "VOICE_TRANS_DATA" ADD CONSTRAINT "VOICE_TRANS_DATA_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VTS_OPERATION_LOG
--------------------------------------------------------

  ALTER TABLE "VTS_OPERATION_LOG" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "VTS_OPERATION_LOG" ADD CONSTRAINT "VTS_OPERATION_LOG_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VTS_SYS_PARAM
--------------------------------------------------------

  ALTER TABLE "VTS_SYS_PARAM" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "VTS_SYS_PARAM" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "VTS_SYS_PARAM" ADD CONSTRAINT "VTS_SYS_PARAM_PK" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUALITY_FREE_QUALITY
--------------------------------------------------------

  ALTER TABLE "QUALITY_FREE_QUALITY" ADD CONSTRAINT "QUALITY_FREE_QUALITY_SAP__FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYS_USER" ("UUID") ENABLE;
 
  ALTER TABLE "QUALITY_FREE_QUALITY" ADD CONSTRAINT "QUALITY_FREE_QUALITY_SAP__FK2" FOREIGN KEY ("UPDATE_USER_ID")
	  REFERENCES "SYS_USER" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUALITY_KEYWORD
--------------------------------------------------------

  ALTER TABLE "QUALITY_KEYWORD" ADD CONSTRAINT "QUALITY_KEYWORD_QUALITY_K_FK1" FOREIGN KEY ("TYPE_ID")
	  REFERENCES "QUALITY_KEYWORD_TYPE" ("UUID") ON DELETE CASCADE ENABLE;
 
  ALTER TABLE "QUALITY_KEYWORD" ADD CONSTRAINT "QUALITY_KEYWORD_SAP_USER_FK1" FOREIGN KEY ("UPDATE_USER_ID")
	  REFERENCES "SYS_USER" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUALITY_KEYWORD_TYPE
--------------------------------------------------------

  ALTER TABLE "QUALITY_KEYWORD_TYPE" ADD CONSTRAINT "QUALITY_KEYWORD_TYPE_SAP__FK1" FOREIGN KEY ("UPDATE_USER_ID")
	  REFERENCES "SYS_USER" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUALITY_MEMBER_TYPE
--------------------------------------------------------

  ALTER TABLE "QUALITY_MEMBER_TYPE" ADD CONSTRAINT "QUALITY_ROLE_TYPE_SYS_USE_FK1" FOREIGN KEY ("UPDATE_USER_ID")
	  REFERENCES "SYS_USER" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUALITY_PRECONDITION
--------------------------------------------------------

  ALTER TABLE "QUALITY_PRECONDITION" ADD CONSTRAINT "QUALITY_PRECONDITION_QUAL_FK1" FOREIGN KEY ("RULE_ID")
	  REFERENCES "QUALITY_RULE" ("UUID") ENABLE;
 
  ALTER TABLE "QUALITY_PRECONDITION" ADD CONSTRAINT "QUALITY_RULE_PRECONDITION_FK1" FOREIGN KEY ("PRECONDITION_TYPE_ID")
	  REFERENCES "QUALITY_PRECONDITION_TYPE" ("UUID") ENABLE;
 
  ALTER TABLE "QUALITY_PRECONDITION" ADD CONSTRAINT "QUALITY_RULE_PRECONDITION_FK2" FOREIGN KEY ("RULES_ID")
	  REFERENCES "QUALITY_RULES" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUALITY_PRECONDITION_TYPE
--------------------------------------------------------

  ALTER TABLE "QUALITY_PRECONDITION_TYPE" ADD CONSTRAINT "QUALITY_RUE_PRECONDITION__FK1" FOREIGN KEY ("UPDATE_USER_ID")
	  REFERENCES "SYS_USER" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUALITY_RULE
--------------------------------------------------------

  ALTER TABLE "QUALITY_RULE" ADD CONSTRAINT "QUALITY_RULE_QUALITY_RULE_FK1" FOREIGN KEY ("RULES_ID")
	  REFERENCES "QUALITY_RULES" ("UUID") ENABLE;
 
  ALTER TABLE "QUALITY_RULE" ADD CONSTRAINT "QUALITY_RULE_QUALITY_RULE_FK2" FOREIGN KEY ("RULE_TYPE_ID")
	  REFERENCES "QUALITY_MEMBER_TYPE" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUALITY_RULES
--------------------------------------------------------

  ALTER TABLE "QUALITY_RULES" ADD CONSTRAINT "QUALITY_RULES_QUALITY_RUL_FK1" FOREIGN KEY ("RULES_TYPE_ID")
	  REFERENCES "QUALITY_RULES_TYPE" ("UUID") ENABLE;
 
  ALTER TABLE "QUALITY_RULES" ADD CONSTRAINT "QUALITY_RULES_SYS_USER_FK1" FOREIGN KEY ("UPDATE_USER_ID")
	  REFERENCES "SYS_USER" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table QUALITY_RULES_TYPE
--------------------------------------------------------

  ALTER TABLE "QUALITY_RULES_TYPE" ADD CONSTRAINT "QUALITY_RULES_TYPE_SAP_US_FK1" FOREIGN KEY ("UPDATE_USER_ID")
	  REFERENCES "SYS_USER" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SYS_OPERATION_LOG
--------------------------------------------------------

  ALTER TABLE "SYS_OPERATION_LOG" ADD CONSTRAINT "SYS_OPERATION_LOG_SAP_USE_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYS_USER" ("UUID") DISABLE;
--------------------------------------------------------
--  Ref Constraints for Table SYS_ROLE_MENU_RELATION
--------------------------------------------------------

  ALTER TABLE "SYS_ROLE_MENU_RELATION" ADD CONSTRAINT "SYS_ROLE_MENU_RELATION_SY_FK2" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "SYS_ROLE" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SYS_USER
--------------------------------------------------------

  ALTER TABLE "SYS_USER" ADD CONSTRAINT "SAP_USER_SAP_USER_FK1" FOREIGN KEY ("UPDATE_USER_ID")
	  REFERENCES "SYS_USER" ("UUID") ENABLE;
 
  ALTER TABLE "SYS_USER" ADD CONSTRAINT "SAP_USER_SYS_USER_GROUP_FK1" FOREIGN KEY ("USER_GROUP_ID")
	  REFERENCES "SYS_USER_GROUP" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SYS_USER_GROUP
--------------------------------------------------------

  ALTER TABLE "SYS_USER_GROUP" ADD CONSTRAINT "SYS_USER_GROUP_SAP_USER_FK1" FOREIGN KEY ("UPDATE_USER_ID")
	  REFERENCES "SYS_USER" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SYS_USER_ROLE_RELATION
--------------------------------------------------------

  ALTER TABLE "SYS_USER_ROLE_RELATION" ADD CONSTRAINT "SYS_USER_ROLE_RELATION_SY_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "SYS_USER" ("UUID") ENABLE;
 
  ALTER TABLE "SYS_USER_ROLE_RELATION" ADD CONSTRAINT "SYS_USER_ROLE_RELATION_SY_FK2" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "SYS_ROLE" ("UUID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VOICE_DATA
--------------------------------------------------------

  ALTER TABLE "VOICE_DATA" ADD CONSTRAINT "VOICE_VOICE_ANALYSIS_DATA_FK1" FOREIGN KEY ("ANALYSIS_DATA_ID")
	  REFERENCES "VOICE_ANALYSIS_DATA" ("UUID") ENABLE;
 
  ALTER TABLE "VOICE_DATA" ADD CONSTRAINT "VOICE_VOICE_MANUAL_DATA_FK1" FOREIGN KEY ("MANUAL_DATA_ID")
	  REFERENCES "VOICE_MANUAL_DATA" ("UUID") ENABLE;
 
  ALTER TABLE "VOICE_DATA" ADD CONSTRAINT "VOICE_VOICE_ONLINE_FK1" FOREIGN KEY ("ONLINE_DATA_ID")
	  REFERENCES "VOICE_ONLINE_DATA" ("UUID") ENABLE;
 
  ALTER TABLE "VOICE_DATA" ADD CONSTRAINT "VOICE_VOICE_QUALITY_DATA_FK1" FOREIGN KEY ("QUALITY_DATA_ID")
	  REFERENCES "VOICE_QUALITY_DATA" ("UUID") ENABLE;
 
  ALTER TABLE "VOICE_DATA" ADD CONSTRAINT "VOICE_VOICE_RELATE_DATA_FK1" FOREIGN KEY ("RELATE_DATA_ID")
	  REFERENCES "VOICE_RELATE_DATA" ("UUID") ENABLE;
 
  ALTER TABLE "VOICE_DATA" ADD CONSTRAINT "VOICE_VOICE_TRANS_DATA_FK1" FOREIGN KEY ("TRANS_DATA_ID")
	  REFERENCES "VOICE_TRANS_DATA" ("UUID") ENABLE;
